#!/usr/bin/env bash
# Builds the Wattson executable via SwiftPM and wraps it in a proper .app
# bundle (Info.plist + entitlements), since `swift build` alone only
# produces a bare Unix binary — Launch Services needs the bundle to honor
# LSUIElement and route wattson:// URLs back to the app.
#
# Usage: scripts/build-app.sh [--client-id TESLA_CLIENT_ID] [--sign "Developer ID Application: Your Name (TEAMID)"]
set -euo pipefail

cd "$(dirname "$0")/.."

CONFIGURATION="release"
APP_NAME="Wattson"
BUILD_DIR=".build/${CONFIGURATION}"
APP_BUNDLE="release/${APP_NAME}.app"
SIGN_IDENTITY=""
CLIENT_ID=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --sign)
      SIGN_IDENTITY="$2"
      shift 2
      ;;
    --client-id)
      CLIENT_ID="$2"
      shift 2
      ;;
    *)
      echo "Unknown argument: $1" >&2
      exit 1
      ;;
  esac
done

# GeneratedConfig.swift ships with a nil placeholder so the repo never
# carries the real client id. When --client-id is passed, bake it in for
# this build only, then revert the file — real value never gets committed.
GENERATED_CONFIG="Sources/Wattson/GeneratedConfig.swift"
if [[ -n "${CLIENT_ID}" ]]; then
  GENERATED_CONFIG_BACKUP="$(mktemp)"
  cp "${GENERATED_CONFIG}" "${GENERATED_CONFIG_BACKUP}"
  trap 'mv "${GENERATED_CONFIG_BACKUP}" "${GENERATED_CONFIG}"' EXIT
  cat > "${GENERATED_CONFIG}" <<SWIFT
// Generated by scripts/build-app.sh --client-id. Reverted after the build —
// see GeneratedConfig.swift's checked-in placeholder.
enum GeneratedConfig {
    static let teslaClientId: String? = "${CLIENT_ID}"
}
SWIFT
else
  echo "No --client-id passed — building with GeneratedConfig's nil placeholder (set WATTSON_TESLA_CLIENT_ID instead for local runs)."
fi

echo "Building ${APP_NAME} (${CONFIGURATION})..."
swift build -c "${CONFIGURATION}"

rm -rf "release"
mkdir -p "${APP_BUNDLE}/Contents/MacOS"
mkdir -p "${APP_BUNDLE}/Contents/Resources"

cp "${BUILD_DIR}/${APP_NAME}" "${APP_BUNDLE}/Contents/MacOS/${APP_NAME}"
cp "Resources/Info.plist" "${APP_BUNDLE}/Contents/Info.plist"
cp "Resources/AppIcon.icns" "${APP_BUNDLE}/Contents/Resources/AppIcon.icns"

if [[ -n "${SIGN_IDENTITY}" ]]; then
  echo "Signing with: ${SIGN_IDENTITY}"
  codesign --deep --force --options runtime \
    --entitlements "Resources/Wattson.entitlements" \
    --sign "${SIGN_IDENTITY}" \
    "${APP_BUNDLE}"
  echo "Signed. Next: notarize with 'xcrun notarytool submit' and staple with 'xcrun stapler staple'."
else
  echo "Ad-hoc signing for local testing (not notarizable) — pass --sign \"Developer ID Application: ...\" for a distributable build."
  codesign --deep --force --sign - "${APP_BUNDLE}"
fi

echo "Built ${APP_BUNDLE}"
